# Generated by Django 4.0.3 on 2022-03-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('name', models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False)),
                ('album', models.CharField(default='SOME STRING', max_length=200)),
                ('genre', models.CharField(default='SOME STRING', max_length=200)),
                ('year', models.IntegerField(default=2000)),
                ('record_company', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='raitings',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artists',
            name='song',
            field=models.CharField(default='SOME STRING', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ratings',
            name='song',
            field=models.ForeignKey(default='SOME STRING', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='ps2.artists'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(default='SOME STRING', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='ps2.users'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist',
            field=models.ForeignKey(default='SOME STRING', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='ps2.attributes'),
        ),
    ]
